package com.example.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.example.demo.entity.Item;
import com.example.demo.repo.ItemRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/api/v1/items") // This means URL's start with /demo (after Application path)
public class MainController {
	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ItemRepository itemRepository;

	
	
	@ResponseStatus(code = HttpStatus.CREATED)
	@PostMapping
	public @ResponseBody Item addNewItem(@RequestBody Item item) {
		item.setId(null);
		return itemRepository.save(item);
	}
	
	
//	@GetMapping("/{id}")
//	public @ResponseBody ResponseEntity<String>
//	  getById(@PathVariable String id) {
//	    return new ResponseEntity<String>("GET Response : "
//	      + id, HttpStatus.OK);
//	}
	
	@GetMapping("/{id}")	
	public @ResponseBody Item getItemById(@PathVariable Long id) {
		System.out.println("*************" + itemRepository.findById(id).isPresent());
		return itemRepository.findById(id).get();
	}
	

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Item> getAllItems() {
		// This returns a JSON or XML with the Items
		return itemRepository.findAll();
	}
}